spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode:   HTML
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html; charset=utf-8

  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

  datasource:
    url: jdbc:mysql://localhost:3306/letsDo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 31415926

    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081
  max-http-header-size: 1048576
